name: clone_empiricus_research
description: "Clone Empiricus Ã© um projeto que fiz para meu processo seletivo afim de mostrar minhas habilidades com Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

  # sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.0.0
  path_provider: ^2.0.0
  flutter_lazy_indexed_stack: ^0.0.6
  animated_theme_switcher: ^2.0.10
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  provider: ^6.1.5+1
  flutter_bloc: ^9.1.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
